/*possible script for user profiles*/
CREATE USER 'user'@'%' IDENTIFIED VIA mysql_native_password USING 'user123';GRANT SELECT, INSERT, UPDATE, CREATE TEMPORARY TABLES, CREATE VIEW, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
                                                                   /* *** */

CREATE USER 'MicroProAdmin'@'%' IDENTIFIED VIA mysql_native_password USING 'pro123';GRANT ALL PRIVILEGES ON *.* TO 'MicroProAdmin'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;